apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: f7udwq0t4-dotnet-basic-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/f7udwq0t4-dotnet-basic-gitops